# Generated by Django 5.2.4 on 2025-07-16 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('entity_type', models.CharField(choices=[('organization', 'Organization'), ('individual', 'Individual'), ('external', 'External Entity'), ('venue', 'Venue'), ('resource', 'Resource')], max_length=20)),
                ('status', models.CharField(default='active', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Store contact info, capabilities, preferences, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('target_completion', models.DateField(blank=True, null=True)),
                ('actual_completion', models.DateField(blank=True, null=True)),
                ('project_data', models.JSONField(blank=True, default=dict, help_text='Budget, milestones, resources, deliverables, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_organization', models.ForeignKey(limit_choices_to={'entity_type': 'organization'}, on_delete=django.db.models.deletion.CASCADE, related_name='primary_projects', to='core.entity')),
                ('related_entities', models.ManyToManyField(blank=True, related_name='involved_projects', to='core.entity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('entry_type', models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense'), ('investment', 'Investment'), ('loan', 'Loan'), ('grant', 'Grant')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('service_fee', 'Service Fee'), ('product_sale', 'Product Sale'), ('subscription', 'Subscription'), ('lesson_fee', 'Lesson Fee'), ('consulting', 'Consulting'), ('license', 'License')], max_length=50)),
                ('description', models.TextField()),
                ('transaction_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('financial_data', models.JSONField(blank=True, default=dict, help_text='Payment method, tax info, invoice details, recurring info, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_finances', to='core.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_finances', to='core.entity')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='core.project')),
            ],
            options={
                'verbose_name': 'Financial Entry',
                'verbose_name_plural': 'Financial Entries',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('business_plan', 'Business Plan'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('meeting_notes', 'Meeting Notes'), ('technical_spec', 'Technical Specification'), ('correspondence', 'Correspondence'), ('report', 'Report'), ('proposal', 'Proposal'), ('policy', 'Policy')], max_length=50)),
                ('content', models.TextField(blank=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('document_data', models.JSONField(blank=True, default=dict, help_text='File info, approval status, version info, tags, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_documents', to='core.entity')),
                ('related_entities', models.ManyToManyField(blank=True, related_name='related_documents', to='core.entity')),
                ('related_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaudeInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('response', models.TextField()),
                ('interaction_type', models.CharField(default='general', max_length=50)),
                ('interaction_data', models.JSONField(blank=True, default=dict, help_text='API parameters, tokens used, context data, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('task_data', models.JSONField(blank=True, default=dict, help_text='Instructions, dependencies, resources, notes, etc.')),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='core.entity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project')),
                ('related_entities', models.ManyToManyField(blank=True, related_name='related_tasks', to='core.entity')),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('entry_method', models.CharField(default='manual', max_length=20)),
                ('tracking_data', models.JSONField(blank=True, default=dict, help_text='Location, tools used, outcomes, WhatsApp data, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'organization'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_time_entries', to='core.entity')),
                ('person', models.ForeignKey(limit_choices_to={'entity_type': 'individual'}, on_delete=django.db.models.deletion.CASCADE, related_name='person_time_entries', to='core.entity')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='core.task')),
            ],
            options={
                'verbose_name': 'Time Entry',
                'verbose_name_plural': 'Time Entries',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('is_tracking_time', models.BooleanField(default=False)),
                ('session_data', models.JSONField(blank=True, default=dict)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_organization', models.ForeignKey(blank=True, limit_choices_to={'entity_type': 'organization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_whatsapp_sessions', to='core.entity')),
                ('active_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.project')),
                ('current_time_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.timeentry')),
                ('entity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entity')),
            ],
        ),
        migrations.CreateModel(
            name='EntityRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('manages', 'Manages'), ('works_for', 'Works For'), ('supplies', 'Supplies'), ('collaborates', 'Collaborates With'), ('teaches', 'Teaches'), ('learns_from', 'Learns From'), ('invests_in', 'Invests In'), ('provides_venue', 'Provides Venue'), ('uses_services', 'Uses Services'), ('shares_resources', 'Shares Resources'), ('client_of', 'Client Of'), ('contractor_for', 'Contractor For')], max_length=50)),
                ('strength', models.IntegerField(default=5, help_text='1-10 scale of relationship importance')),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('relationship_data', models.JSONField(blank=True, default=dict, help_text='Contract terms, shared projects, communication preferences, etc.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_a', to='core.entity')),
                ('entity_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_b', to='core.entity')),
            ],
            options={
                'verbose_name': 'Entity Relationship',
                'unique_together': {('entity_a', 'entity_b', 'relationship_type')},
            },
        ),
    ]
